In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
a.shape

(3,)

In [6]:
type(a)

numpy.ndarray

In [7]:
a[0] = 10

In [8]:
a

array([10,  2,  3])

In [9]:
for i in a:
    print(i)

10
2
3


In [11]:
b = np.array([
    [1,2,3],
    [4,5,6]
])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b.shape

(2, 3)

In [13]:
type(b)

numpy.ndarray

In [14]:
b[0][0], b[0][1], b[0,2]

(np.int64(1), np.int64(2), np.int64(3))

In [15]:
b[1,0], b[1,1], b[1,2]

(np.int64(4), np.int64(5), np.int64(6))

In [16]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
a = np.eye(3,6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [18]:
a = np.zeros((4,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
b.dtype

dtype('int64')

In [21]:
a.dtype


dtype('float64')

In [22]:
c = np.array([1, 3.4, True])
c.dtype

dtype('float64')

In [24]:
c = np.array([1, 3.4, True, 'asfd', [3, False]])
c.dtype

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [25]:
np.full(3, 14)

array([14, 14, 14])

In [26]:
np.full((4,6), 42)

array([[42, 42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42, 42]])

In [27]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.random.random((4,3))

array([[0.33717077, 0.20468899, 0.2876954 ],
       [0.16341014, 0.507198  , 0.14846354],
       [0.89727163, 0.80182549, 0.40948959],
       [0.91110039, 0.53292608, 0.47979691]])

In [29]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

In [30]:
a[:, ]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
a[:, 1:-1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [34]:
c = a[1:, 1:-1]
c

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [36]:
c[1,1] = 100
c

array([[  6,   7],
       [ 10, 100],
       [ 14,  15]])

In [37]:
a

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10, 100,  12],
       [ 13,  14,  15,  16]])

In [39]:
a_copy = a[1:, 1:-1].copy()

In [40]:
a_copy

array([[  6,   7],
       [ 10, 100],
       [ 14,  15]])

In [41]:
a

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10, 100,  12],
       [ 13,  14,  15,  16]])

In [42]:
c

array([[  6,   7],
       [ 10, 100],
       [ 14,  15]])

In [43]:
x = np.array([
    [1,2],
    [3,4]
])
y = np.array([
    [5,6],
    [7,8]
])

In [44]:
x+y

array([[ 6,  8],
       [10, 12]])

In [45]:
x-y

array([[-4, -4],
       [-4, -4]])

In [46]:
x*y

array([[ 5, 12],
       [21, 32]])

In [47]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [48]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [49]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [50]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [51]:
np.subtract(x,y)


array([[-4, -4],
       [-4, -4]])

In [52]:
x+2

array([[3, 4],
       [5, 6]])

In [53]:
3.4*x

array([[ 3.4,  6.8],
       [10.2, 13.6]])

In [54]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [55]:
np.power(x,2)

array([[ 1,  4],
       [ 9, 16]])

In [56]:
A = np.array([
    [2,0],
    [0,2]
])
b = np.array([3.4, 7.8])

In [57]:
A_inv = np.linalg.inv(A)

In [58]:
A_inv

array([[0.5, 0. ],
       [0. , 0.5]])

In [60]:
x = np.dot(A_inv, b)
x

array([1.7, 3.9])

In [61]:
A.dot(x)

array([3.4, 7.8])

In [62]:
x = np.array([1,5,2,3,7,8,4,6])

In [63]:
np.max(x)

np.int64(8)

In [64]:
np.argmax(x)

np.int64(5)

In [65]:
x == 3

array([False, False, False,  True, False, False, False, False])

In [71]:
x = np.array([1,5,2,3,7,8,4,6,3,3,6,3])
index = x == 3

In [72]:
index

array([False, False, False,  True, False, False, False, False,  True,
        True, False,  True])

In [73]:
x[index]

array([3, 3, 3, 3])

In [74]:
x[(x>5) & (x%2==0)]

array([8, 6, 6])